name: Test
on:
  push:
    branches:
      - 'master'
jobs:
  run_sls:
    name: SLS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        run: npm install
      - name: Invoke
        run: sls invoke local -f harvey   