name: Test
on:
  push:
    branches:
      - 'master'
jobs:
  run_sls:
    name: SLS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [12.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        run: |
              npm install
              npm i -g serverless
      - name: Invoke
        run: sls invoke local -f harvey   